INSERT INTO seeds(category,name,content,enabled,created_at) VALUES
-- ===== 世界观 genre =====
('genre','xianxia','东方仙侠；宗门、秘境、法宝、灵脉、因果；力量体系以炼气、筑基、金丹、元婴、化神、炼虚、合体、大乘为参考。',1,unixepoch()),
('genre','wuxia','江湖武侠；门派、帮会、镖局、朝堂与江湖交织；力量体系以内功、轻功、招式、宗师境界为参考。',1,unixepoch()),
('genre','ancient','古代朝堂；王朝、君臣、科举、边关与朝堂博弈；重礼制与人情，武力为辅。',1,unixepoch()),
('genre','alternate_history','架空王朝；虚构大陆与国家，多势力并立，权谋争霸与战争并行；力量体系可含低超自然。',1,unixepoch()),
('genre','primordial','洪荒神话；上古天地、巫妖封神、神兽与神祇并存；力量体系以神位、血脉、功德为参考。',1,unixepoch()),
('genre','palace','宫廷宅斗；后宫、世家、宅门内院；表面风平浪静，底下人情算计与利益纠葛。',1,unixepoch()),
('genre','urban','现代都市；学校、公司、城市生活、网络与现实社会规则并存；超自然元素可低烈度存在。',1,unixepoch()),
('genre','campus','校园青春；高中或大学校园，社团、考试、青春萌动与成长；人际关系简单但细腻。',1,unixepoch()),
('genre','workplace','职场商战；公司、行业竞争、商业谈判与办公室政治；重资源、人脉与决策。',1,unixepoch()),
('genre','entertainment','娱乐圈；演艺公司、镜头前后、粉丝舆论与资源争夺；表面光鲜背后有明暗规则。',1,unixepoch()),
('genre','esports','电竞游戏；战队、比赛、直播、虚拟与现实交织；团队配合与个人天赋并存。',1,unixepoch()),
('genre','fantasy','西方幻想；王国、魔法学院、遗迹、龙与精灵；力量体系以元素、魔法等级与契约为参考。',1,unixepoch()),
('genre','medieval','中世纪骑士；城堡、领主、骑士团、教廷与十字军；重荣誉、誓言与领地。',1,unixepoch()),
('genre','vampire','血族狼人；暗夜、血族氏族、狼人部落与人类社会暗面；永生、血脉与狩猎。',1,unixepoch()),
('genre','norse','北欧神话；阿斯加德、九界、诸神黄昏、巨人与英灵；命运与预言贯穿始终。',1,unixepoch()),
('genre','scifi','近未来科幻；巨型都市、人工智能、义体与企业势力；力量体系以科技与权限为参考。',1,unixepoch()),
('genre','interstellar','星际文明；星际航行、外星文明、联邦与帝国、舰队与殖民；科技水平远超地球。',1,unixepoch()),
('genre','cyberpunk','赛博朋克；霓虹都市、义体改造、巨型企业垄断、地下黑客；高科技低生活。',1,unixepoch()),
('genre','apocalypse','灾后求生；资源、避难所、异变、聚落与人性选择；力量体系以装备、适应与异能为参考。',1,unixepoch()),
('genre','cthulhu','克苏鲁式神秘；旧神、禁忌知识、梦境、调查与不可名状的恐惧；真相逐层解锁。',1,unixepoch()),
('genre','infinite','无限流副本；不断进入不同规则世界完成任务，生存与通关为核心；每个副本规则不同。',1,unixepoch()),
('genre','quick_transmigration','快穿世界；灵魂穿越到不同小世界完成任务，每个世界剧情独立；身份与记忆按世界刷新。',1,unixepoch()),
('genre','rebirth','重生穿越；带着前世记忆回到过去，改变命运；蝴蝶效应明显，选择改变结局。',1,unixepoch()),
('genre','supernatural','灵异恐怖；鬼怪、阴阳眼、风水命理；日常中藏着超自然，真相逐渐逼近。',1,unixepoch()),
('genre','mystery','悬疑推理；案件、线索、不在场证明与真凶；重逻辑与证据，人心比案件更复杂。',1,unixepoch()),

-- ===== 关系 relationship =====
('relationship','BG','异性情感线可自然形成；关系由剧情与好感推进。',1,unixepoch()),
('relationship','BL','同性男性情感线可自然形成；关系由剧情与好感推进。',1,unixepoch()),
('relationship','GL','同性女性情感线可自然形成；关系由剧情与好感推进。',1,unixepoch()),
('relationship','beastman','兽人世界观；兽耳、兽尾、部落与发情期设定；种族差异影响情感关系。',1,unixepoch()),
('relationship','poly','多角关系网；多个角色间情感纠葛并存，关系随选择分化，不唯一。',1,unixepoch()),
('relationship','nonhuman','跨种族情感线；人与妖、神、精灵、AI、机械等非人生物之间的感情。',1,unixepoch()),
('relationship','none','不预设恋爱关系，以伙伴、宿敌、师友等关系为主。',1,unixepoch()),

-- ===== 剧情 plot =====
('plot','mystery','悬疑调查；线索分阶段出现，隐藏信息在满足条件后才可见。',1,unixepoch()),
('plot','revenge','复仇与因果；人物过去会逐步影响当前事件。',1,unixepoch()),
('plot','conspiracy','势力阴谋；线索通过遭遇、事件与关系逐渐拼合。',1,unixepoch()),
('plot','adventure','冒险探索；地点、事件与人物推动开放式旅程。',1,unixepoch()),
('plot','growth','成长主线；玩家选择会改变技能、关系与事件阶段。',1,unixepoch()),
('plot','slowburn','慢热关系；互动、共同经历和关键事件逐步积累情感。',1,unixepoch()),
('plot','system','系统任务流；世界存在系统面板，完成任务获得能力或奖励，任务链推动主线。',1,unixepoch()),
('plot','conquest','争霸天下；势力扩张、地盘争夺、天下棋局；玩家可选择辅佐或称霸。',1,unixepoch()),
('plot','building','文明建设；从零建立聚落或势力，经营发展，资源与人口管理。',1,unixepoch()),
('plot','ruins','秘境探险；古墓、遗迹、秘境寻宝，危险与收获并存。',1,unixepoch()),
('plot','business','商战经营；商业博弈、资源争夺、产业扩张。',1,unixepoch()),
('plot','infinite_dungeon','无限副本；不断进入不同规则世界副本，通关求生。',1,unixepoch()),
('plot','harem_palace','宫斗宅斗；后宫或世家宅门中的人情与权谋，上位与自保并存。',1,unixepoch()),
('plot','sweet','甜宠日常；轻松甜蜜，情感互动为主，冲突较轻。',1,unixepoch()),
('plot','marriage_first','先婚后爱；先有婚约或婚姻，感情在相处中逐步培养。',1,unixepoch()),
('plot','transmigrate_novel','穿书逆袭；穿入书中角色，改变原有命运线。',1,unixepoch()),
('plot','face_slap','虐渣打脸；反击欺压者，逐步翻盘。',1,unixepoch()),
('plot','wealthy_clan','豪门恩怨；大家族内部的恩怨与利益纠葛。',1,unixepoch()),
('plot','dark','暗黑致郁；世界残酷，道德灰色，选择有沉重代价，没有完美结局。',1,unixepoch()),
('plot','forbidden','禁忌纠葛；违背世俗常规的情感关系，张力强，代价大。',1,unixepoch()),

-- ===== 事件 event =====
('event','first','第一次行动会让世界发生可追踪的回应。',1,unixepoch()),
('event','encounter','角色遭遇必须发生在实际剧情中，不可由私聊伪造。',1,unixepoch()),
('event','clue','隐藏线索按照条件和阶段解锁，不提前泄露。',1,unixepoch()),
('event','free_explore','玩家自由行动推动世界，无固定主线，探索即剧情。',1,unixepoch()),
('event','causal_chain','每个行动都会引发因果链反应，影响后续发展。',1,unixepoch()),
('event','dialogue_key','关键对话解锁新线索、新地点、新人物态度。',1,unixepoch()),
('event','daily_interact','与角色的日常互动积累关系，偶然触发小事件。',1,unixepoch()),
('event','branch_choice','重要选择导致不同剧情线，世界状态随选择分化。',1,unixepoch()),
('event','daily_life','随机日常事件丰富世界质感，NPC有自己的生活节奏。',1,unixepoch()),
('event','relation_shift','角色之间关系随事件自然变化，不固定阵营。',1,unixepoch()),

-- ===== 性格-表层 personality_outer =====
('personality_outer','热情开朗','待人主动，爱笑，容易熟络，愿意照顾气氛。',1,unixepoch()),
('personality_outer','阳光乐天','遇事往好处想，挫折恢复快。',1,unixepoch()),
('personality_outer','爽朗直率','有话直说，不拐弯抹角，讨厌虚伪客套。',1,unixepoch()),
('personality_outer','活泼灵动','好奇心强，想法多，喜欢新鲜事物。',1,unixepoch()),
('personality_outer','仗义热忱','朋友有难主动出手，重视情义与信任。',1,unixepoch()),
('personality_outer','自信强势','做事果断，敢于表达观点，有领导力。',1,unixepoch()),
('personality_outer','清冷内敛','话不多，安静沉稳，情绪不外露。',1,unixepoch()),
('personality_outer','温柔慢热','初次疏离，熟悉后才敞开心扉，共情强。',1,unixepoch()),
('personality_outer','理智沉静','遇事冷静，优先思考利弊，不冲动。',1,unixepoch()),
('personality_outer','敏感共情','容易察觉别人情绪，体贴细心。',1,unixepoch()),
('personality_outer','独立寡言','习惯自己解决问题，不爱麻烦别人。',1,unixepoch()),
('personality_outer','隐忍坚韧','承受压力不诉苦，默默坚持。',1,unixepoch()),
('personality_outer','暴躁直率','情绪写脸上，来得快去得快，内心单纯无城府。',1,unixepoch()),
('personality_outer','浮夸张扬','喜欢吸引目光，爱讲故事，渴望被关注。',1,unixepoch()),
('personality_outer','支配强势','习惯安排别人，喜欢主导一切。',1,unixepoch()),
('personality_outer','讨好型','对所有人友善，不敢拒绝，不停照顾别人感受。',1,unixepoch()),
('personality_outer','孤僻疏离','主动避开人群，不愿建立关系。',1,unixepoch()),
('personality_outer','悲观多虑','遇事预想最坏结果，容易内耗。',1,unixepoch()),
('personality_outer','阴郁敏感','容易多想，把无心的话往坏处解读。',1,unixepoch()),
('personality_outer','固执闷葫芦','认定的想法很难改变，委屈也不说。',1,unixepoch()),

-- ===== 性格-内核 personality_inner =====
('personality_inner','外冷内热','外表冷淡话少，内心默默记住别人需求，关键时刻出手。',1,unixepoch()),
('personality_inner','嘴硬心软','喜欢吐槽说反话，不肯示弱，但不忍心看别人受苦。',1,unixepoch()),
('personality_inner','外柔内刚','看起来温和好说话，底线极强，触碰原则时绝不退让。',1,unixepoch()),
('personality_inner','外凶内怯','故作凶狠摆出戒备，内心胆怯，用强势伪装保护自己。',1,unixepoch()),
('personality_inner','洒脱执念','平时随性看淡一切，唯独放不下某段过往或某人。',1,unixepoch()),
('personality_inner','理智感性','做事讲逻辑冷静，遇到在意的人情绪会冲破理智。',1,unixepoch()),
('personality_inner','玩世责任','爱开玩笑吊儿郎当，重要时刻绝不掉链子。',1,unixepoch()),
('personality_inner','理想主义','坚守信念，愿意为信念付出代价。',1,unixepoch()),
('personality_inner','现实主义','看清现实，优先生存，不相信空谈理想。',1,unixepoch()),
('personality_inner','犬世','看透世事，习惯性嘲讽，很难相信善意。',1,unixepoch()),
('personality_inner','守序善良','严守规则，坚守底线，不为目的不择手段。',1,unixepoch()),
('personality_inner','灰色中立','没有绝对善恶，视情况权衡，灵活变通。',1,unixepoch()),
('personality_inner','钝感力','不容易被流言小事影响，情绪稳定。',1,unixepoch()),
('personality_inner','高共情','极易感知他人痛苦，容易被情绪拖累。',1,unixepoch()),
('personality_inner','情感淡漠','很难感受到强烈喜怒哀乐，不是冷血，是情绪感知弱。',1,unixepoch()),
('personality_inner','冲动型','容易被情绪带着行动，事后才后悔。',1,unixepoch()),
('personality_inner','傲娇','口是心非，害羞不肯承认心意。',1,unixepoch()),
('personality_inner','病娇','占有欲极强，害怕失去，极端情况下会偏激。',1,unixepoch()),
('personality_inner','佛系','看淡得失，不爱争抢，随遇而安。',1,unixepoch()),
('personality_inner','多疑','很难信任任何人，习惯性怀疑动机。',1,unixepoch()),
('personality_inner','圣母心','不忍心伤害任何人，容易被人利用。',1,unixepoch()),
('personality_inner','厌世','对世界失去期待，麻木，缺乏动力。',1,unixepoch()),

-- ===== 性格-缺陷 personality_flaw =====
('personality_flaw','说话伤人','心直口快，经常不经意间得罪人。',1,unixepoch()),
('personality_flaw','多疑不信','很难信任他人，反复试探。',1,unixepoch()),
('personality_flaw','情绪失控','压力大时容易爆发，事后后悔。',1,unixepoch()),
('personality_flaw','过度讨好','不敢拒绝，委屈自己满足别人。',1,unixepoch()),
('personality_flaw','占有欲强','害怕被抛弃，容易过度干涉对方。',1,unixepoch()),
('personality_flaw','逃避冲突','遇到矛盾就沉默躲开，不解决问题。',1,unixepoch()),
('personality_flaw','过度敏感','别人无心一句话就想很久。',1,unixepoch()),
('personality_flaw','固执己见','听不进别人意见，撞了南墙也不回头。',1,unixepoch()),
('personality_flaw','控制欲强','什么都要按自己的来，不信任别人。',1,unixepoch()),
('personality_flaw','悲观内耗','凡事往坏处想，消耗自己也影响身边人。',1,unixepoch()),
('personality_flaw','口是心非','明明关心却说反话，容易被误解。',1,unixepoch()),
('personality_flaw','不善表达','心里有话说不出口，被当成冷漠。',1,unixepoch()),

-- ===== 角色种子 character =====
('character','冷峻师尊','外冷内稳；擅长观察与保护；与玩家存在未公开的缘分线。',1,unixepoch()),
('character','温柔医者','擅长疗愈与知识；对细节敏感；常在危急时刻提供帮助。',1,unixepoch()),
('character','危险盟友','立场复杂；信守自己的规则；关系会随剧情选择变化。',1,unixepoch()),
('character','活泼旅者','好奇、机敏；喜欢新奇事物；容易发现环境异常。',1,unixepoch()),
('character','沉稳首领','有资源、有责任感；重视契约与势力平衡。',1,unixepoch()),
('character','孤独学者','理性、固执；掌握一部分世界规则与历史。',1,unixepoch()),
('character','直率竞争者','好胜、讲义气；容易在竞争中建立关系。',1,unixepoch()),
('character','慢热新人','谨慎、善良；成长空间大；秘密会随着事件揭开。',1,unixepoch()),
('character','隐秘观察者','寡言、难以读懂；知道部分隐藏线索，但不会轻易公开。',1,unixepoch()),
('character','商业天才','精明、会算账；表面和气，实际利益分明。',1,unixepoch()),
('character','落魄贵族','曾经显赫，如今低调；藏着过去的秘密。',1,unixepoch()),
('character','叛逆弟子/下属','不服管教，有自己的想法；能力强但不守规矩。',1,unixepoch()),
('character','神秘商贩','走南闯北，消息灵通；只认利益不认人。',1,unixepoch()),
('character','退役老兵','见惯生死；话少但可靠；有不为人知的过去。',1,unixepoch()),
('character','天才少女/少年','天赋极高但情商低；不谙世事，容易被利用。',1,unixepoch()),
('character','双面间谍','在两方之间周旋；没人知道他真正效忠谁。',1,unixepoch())
;
