INSERT INTO seeds(category,name,content,enabled,created_at) VALUES
('genre','xianxia','东方仙侠；宗门、秘境、法宝、灵脉、因果；力量体系以炼气、筑基、金丹、元婴、化神、炼虚、合体、大乘为参考。',1,unixepoch()),
('genre','wuxia','江湖武侠；门派、帮会、镖局、朝堂与江湖交织；力量体系以内功、轻功、招式、宗师境界为参考。',1,unixepoch()),
('genre','urban','现代都市；学校、公司、城市生活、网络与现实社会规则并存；超自然元素可低烈度存在。',1,unixepoch()),
('genre','fantasy','西方幻想；王国、魔法学院、遗迹、龙与精灵；力量体系以元素、魔法等级与契约为参考。',1,unixepoch()),
('genre','sci-fi','近未来科幻；巨型都市、人工智能、星际航行、义体与企业势力；力量体系以科技与权限为参考。',1,unixepoch()),
('genre','apocalypse','灾后求生；资源、避难所、异变、聚落与人性选择；力量体系以装备、适应与异能为参考。',1,unixepoch()),
('genre','cthulhu','克苏鲁式神秘；旧神、禁忌知识、梦境、调查与不可名状的恐惧；真相逐层解锁。',1,unixepoch()),
('relationship','BG','异性情感线可自然形成；关系由剧情与好感推进。',1,unixepoch()),
('relationship','BL','同性男性情感线可自然形成；关系由剧情与好感推进。',1,unixepoch()),
('relationship','GL','同性女性情感线可自然形成；关系由剧情与好感推进。',1,unixepoch()),
('relationship','none','不预设恋爱关系，以伙伴、宿敌、师友等关系为主。',1,unixepoch()),
('plot','mystery','悬疑调查；线索分阶段出现，隐藏信息在满足条件后才可见。',1,unixepoch()),
('plot','revenge','复仇与因果；人物过去会逐步影响当前事件。',1,unixepoch()),
('plot','conspiracy','势力阴谋；线索通过遭遇、事件与关系逐渐拼合。',1,unixepoch()),
('plot','adventure','冒险探索；地点、事件与人物推动开放式旅程。',1,unixepoch()),
('plot','growth','成长主线；玩家选择会改变技能、关系与事件阶段。',1,unixepoch()),
('plot','slowburn','慢热关系；互动、共同经历和关键事件逐步积累情感。',1,unixepoch()),
('event','first','第一次行动会让世界发生可追踪的回应。',1,unixepoch()),
('event','encounter','角色遭遇必须发生在实际剧情中，不可由私聊伪造。',1,unixepoch()),
('event','clue','隐藏线索按照条件和阶段解锁，不提前泄露。',1,unixepoch())
,('character','冷峻师尊','外冷内稳；擅长观察与保护；与玩家存在未公开的缘分线。',1,unixepoch())
,('character','温柔医者','擅长疗愈与知识；对细节敏感；常在危急时刻提供帮助。',1,unixepoch())
,('character','危险盟友','立场复杂；信守自己的规则；关系会随剧情选择变化。',1,unixepoch())
,('character','活泼旅者','好奇、机敏；喜欢新奇事物；容易发现环境异常。',1,unixepoch())
,('character','沉稳首领','有资源、有责任感；重视契约与势力平衡。',1,unixepoch())
,('character','孤独学者','理性、固执；掌握一部分世界规则与历史。',1,unixepoch())
,('character','直率竞争者','好胜、讲义气；容易在竞争中建立关系。',1,unixepoch())
,('character','慢热新人','谨慎、善良；成长空间大；秘密会随着事件揭开。',1,unixepoch())
,('character','隐秘观察者','寡言、难以读懂；知道部分隐藏线索，但不会轻易公开。',1,unixepoch())
;
