name = "cardworld"
main = "src/worker.js"
compatibility_date = "2026-09-01"
assets = { directory = "./public", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "cardworld"
database_id = "REPLACE_WITH_D1_DATABASE_ID"

[triggers]
crons = ["*/15 * * * *"]
